// <auto-generated />
using System;
using System.Collections.Generic;
using ContasEmDia.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContasEmDia.Infrastructure.Migrations
{
    [DbContext(typeof(ContasEmDiaDbContext))]
    [Migration("20260906105126_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContasEmDia.Domain.Aggregates.RecurringExpense", b =>
                {
                    b.Property<Guid>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<int>("_category")
                        .HasColumnType("integer")
                        .HasColumnName("Category");

                    b.Property<int>("_dueDay")
                        .HasColumnType("integer")
                        .HasColumnName("DueDay");

                    b.Property<int>("_frequency")
                        .HasColumnType("integer")
                        .HasColumnName("Frequency");

                    b.Property<decimal>("_monthlyAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("MonthlyAmount");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Name");

                    b.Property<string>("_note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Note");

                    b.Property<DateOnly>("_startDate")
                        .HasColumnType("date")
                        .HasColumnName("StartDate");

                    b.Property<int>("_status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.HasKey("_id");

                    b.ToTable("RecurringExpenses", (string)null);
                });

            modelBuilder.Entity("ContasEmDia.Domain.Entities.Occurrence", b =>
                {
                    b.Property<Guid>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("RecurringExpenseId")
                        .HasColumnType("uuid");

                    b.Property<int>("_category")
                        .HasColumnType("integer")
                        .HasColumnName("Category");

                    b.Property<DateOnly>("_dueDate")
                        .HasColumnType("date")
                        .HasColumnName("DueDate");

                    b.Property<decimal>("_expectedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("ExpectedAmount");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Name");

                    b.Property<int>("_status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "_referencePeriod", "ContasEmDia.Domain.Entities.Occurrence._referencePeriod#ReferencePeriod", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Month")
                                .HasColumnType("integer")
                                .HasColumnName("ReferenceMonth");

                            b1.Property<int>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("ReferenceYear");
                        });

                    b.HasKey("_id");

                    b.HasIndex("RecurringExpenseId");

                    b.ToTable("Occurrences", (string)null);
                });

            modelBuilder.Entity("ContasEmDia.Domain.Entities.Occurrence", b =>
                {
                    b.HasOne("ContasEmDia.Domain.Aggregates.RecurringExpense", null)
                        .WithMany("_occurrences")
                        .HasForeignKey("RecurringExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContasEmDia.Domain.Aggregates.RecurringExpense", b =>
                {
                    b.Navigation("_occurrences");
                });
#pragma warning restore 612, 618
        }
    }
}
